# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Last Chair
email: thelastchairnh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thelastchairnh.com" # the base hostname & protocol for your site
street_address: 5 NH-25
city_state_zip: Plymouth, NH 03264
google_place_link: "https://www.google.com/maps/place/The+Last+Chair/@43.7702953,-71.7648951,17z/data=!4m5!3m4!1s0x4cb35f1eebff6707:0xf6577367fecd5d93!8m2!3d43.7702953!4d-71.7627064"
phone: (603) 238-9077
phone_tel: 16032389077

# Build settings
markdown: kramdown
version: 3.0.3

collections:
  menu_items:
    output: false

defaults:
  - scope:
      path: ""
      type: "menu_item"
    values:
      layout: "menu-item"

_comments:
  title: The page metatitle
  heading: Main page heading
  content_html: Main page content
  phone_tel: Phone number as numbers only